### ISSUE TITLE
Release-plz github action fails on git command

### ISSUE THREAD

**Issue by vhdirk** [MarcoIeni/release-plz#1479] opened 2024-05-21 14:47 UTC
## Bug description

I have a crate where I'd like to use release-plz for, you guessed it, release management: https://github.com/vhdirk/dash7-rs
I tried to follow the docs as close as possible, ending up with: https://github.com/vhdirk/dash7-rs/blob/main/.release-plz.toml and https://github.com/vhdirk/dash7-rs/blob/main/.github/workflows/release.yml (I have verified that the keys used in the github action do exist).

However, upon running release-plz in CI, it fails by just displaying the help message for `git`:

```
Run MarcoIeni/git-config@v0.1
Run # The environment variable GITHUB_TOKEN is read by the `gh` cli
usage: git config [<options>]

Config file location
    --[no-]global         use global config file
    --[no-]system         use system config file

```
See here for full log: https://github.com/vhdirk/dash7-rs/actions/runs/9175702983/job/25229246242

- Would you like to work on a fix?
Yes, but I suppose my own config is lacking something

**Comment by MarcoIeni** [comment] 2024-05-21 16:21
Does it work with the default github token?

**Comment by vhdirk** [comment] 2024-05-21 18:55
That does indeed seem to go a bit further. I'm now hitting some other config issues, but that's outside scope for this report

**Comment by MarcoIeni** [comment] 2024-05-21 19:44
ok, you are also missing this:
![image](https://github.com/MarcoIeni/release-plz/assets/11428655/d925dd9d-d8b5-4364-b500-f90d829e0bf1)

**Comment by MarcoIeni** [comment] 2024-05-21 20:01
I also opened https://github.com/MarcoIeni/git-config/pull/1 to show a better error message

**Comment by MarcoIeni** [comment] 2024-05-21 21:35
I saw you applied these suggestions but you are still getting the same error 🤔 
Can you fork or inline https://github.com/MarcoIeni/git-config/ and try to add debug statements e.g. print `VIEWER_JSON`, so that we understand where the issue is?
As an outcome of this it would be great if we could add a meaningful error message to git-config.

**Comment by vhdirk** [comment] 2024-05-22 08:27
I figured it out: https://github.com/MarcoIeni/git-config/pull/2

**Comment by MarcoIeni** [comment] 2024-05-22 16:54
thanks! merged and released. Can you try release-plz again? 🙏

**Closed** 2024-09-07 13:31 UTC
Labels: bug
