### ISSUE TITLE
Trouble with uncommitted changes in `Cargo.lock` with `release-plz update`

### ISSUE THREAD

**Issue by sdwilsh** [MarcoIeni/release-plz#1286] opened 2024-02-21 05:56 UTC
## Bug description

In a newly setup configuration, CI and `release-plz update` fails with:
```
Error: failed to determine next versions

Caused by:
    the working directory of this project has uncommitted changes. Please commit or stash these changes:
    ["Cargo.lock"]
```

I'm fairly new to Rust, so it's very possible I'm just doing it wrong, but I get no changes to `Cargo.lock` when I run `cargo update`, so I'm not sure why `Cargo.lock` is becoming dirty when `release-plz` runs.  The temporary directory that `release-plz` clones into gets deleted, which makes it hard to debug what the changes might be as well (having a flag to let it hang around might be a feature request I can file if there is interest).

- Would you like to work on a fix? yes, even if it's to improve the docs to make whatever mistake I might have made more clear

## To Reproduce

1.` git clone https://github.com/sdwilsh/jellyfin-remote-proxy.git`
2. `cd jellyfin-remote-proxy`
3. `release-plz update`

## Expected behavior

The CI workflow and `release-plz update` runs successfully.

## Environment

- OS: Ubuntu 22.04
- release-plz version: 0.3.45

## Additional context

My workflow is copied verbatim from the [docs](https://release-plz.ieni.dev/docs/github/quickstart#example-release-pr-and-release), with a version selector added there, and you can see this failing in CI as well [here](https://github.com/sdwilsh/jellyfin-remote-proxy/actions?query=workflow%3ARelease-plz).

**Comment by MarcoIeni** [comment] 2024-02-21 17:40
The issue is that your `Cargo.lock` is committed, but it is also in `.gitignore`.
I have seen many users do this mistake.
If you want to open a PR to add this check [here](https://github.com/isidzukuri/release-plz/blob/c6d8928daebdc7f8fa15e997368d735735eb90c4/crates/release_plz_core/src/next_ver.rs#L374) (just before the if) it would be awesome!

You should check if Cargo.lock is present and if it is in the `.gitignore` file.
You can find the path of the Cargo.lock by using the `input.local_manifest` field. I.e. you just need to change the file extension: `Cargo.toml` -> `Cargo.lock`.
You could also add an integration test for this. You can take inspiration from:
- https://github.com/MarcoIeni/release-plz/blob/e50dc2bee8ea436c48cc3be1a339185655439862/crates/release_plz/tests/all/release.rs#L28
- https://github.com/MarcoIeni/release-plz/blob/e50dc2bee8ea436c48cc3be1a339185655439862/crates/release_plz/tests/all/changelog.rs#L5

**Comment by sdwilsh** [comment] 2024-02-22 00:28
>  I have seen many users do this mistake.

That's probably because it's what `cargo` generated, and I didn't read the comment where it says you need to remove it if it's a binary!

I'll keep this open to add better messaging per your suggestion.

**Closed** 2024-02-27 22:00 UTC
Labels: bug
