### ISSUE TITLE
changelog: the `unreleased` section is not deleted but added again

### ISSUE THREAD

**Issue by sassman** [MarcoIeni/release-plz#1387] opened 2024-04-08 12:39 UTC
As you can see above, release-plz tries to re-add another `Unreleased` section to the Changelog file.

![image](https://github.com/MarcoIeni/release-plz/assets/329682/4289bd70-138f-4209-b0db-e9314d15ffce)

This is the origin of the screenshot:
https://github.com/cargo-generate/cargo-generate/pull/1164/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed

**Comment by MarcoIeni** [comment] 2024-04-17 21:13
Hey Sven 👋 

I see that the Unreleased section is in the body in your configuration, so I think it is expected that the Ureleased section is repeated.

Does git-cliff behaves in the way that you expect? 🤔 

Ideally we would put the Unreleased section in the header, but git-cliff can't customize it with the version. So maybe what you want is not achievable with git-cliff 🤔 

I tried a hacky solution in https://github.com/MarcoIeni/release-plz/pull/1403 but it still needs some work

**Comment by sassman** [comment] 2024-04-18 22:39
Hey Marco, 

I think I finally understood how I have to configure git-cliff.
I'll give it a try, maybe your hack is then not needed at all and we can provide a configuration that leads to the same effect. :)

**Comment by MarcoIeni** [comment] 2024-04-19 10:42
that sounds great, thanks!

**Comment by MarcoIeni** [comment] 2024-04-23 20:27
I'll close this issue because it's not a bug in release-plz.
Let's continue the discussion in https://github.com/MarcoIeni/release-plz/issues/1367 👍

**Closed by MarcoIeni** 2024-04-23 20:27 UTC
Labels: bug

**Comment by pedronauck** [comment] 2025-01-29 14:27
hey @sassman can you share how you figured out to solve this?
