### ISSUE TITLE
Release commits become Unverified after force push

### ISSUE THREAD

**Issue by Pr0methean** [MarcoIeni/release-plz#1443] opened 2024-05-06 02:23 UTC
## Bug description

When a release PR is force-pushed, the new commit displays as Unverified even though the original commit displayed as Verified.

- Would you like to work on a fix? [y]

## To Reproduce

1. Enable the GitHub Action.
2. Configure it to use a Personal Access Token (PAT).
3. Enable signature verification in the default branch's ruleset.
4. Push a commit that triggers a release PR.
5. While the release PR is open, push another commit that triggers an update.

## Expected behavior

The release PR always consists of a Verified commit.

## Environment

- OS: macOS Sonoma 14.4.1
- release-plz version: 0.3.65

## Additional context

An example of an Actions run that produced an unverified commit was https://github.com/zip-rs/zip2/actions/runs/8962859565/job/24612329930.

**Comment by MarcoIeni** [comment] 2024-05-06 05:52
Duplicate of #1406

**Closed** 2024-05-06 05:52 UTC
Labels: bug
