### ISSUE TITLE
release-pr is created wrong

### ISSUE THREAD

**Issue by flying-sheep** [MarcoIeni/release-plz#756] opened 2023-05-05 12:07 UTC
## Bug description

flying-sheep/xdot-rs#29 was created with conflicts and wrong changes (the diff displayed by GitHub seems to include a lot of changes that have been made long ago)

- Would you like to work on a fix? n

## To Reproduce

Unknown

## Expected behavior

PR is created with just changes to package version and changelog

## Environment

- OS: N/A
- release-plz version: 0.5

**Comment by MarcoIeni** [comment] 2023-05-05 20:47
Thank you for reporting the issue.
This also happened to me. I reported it in https://github.com/MarcoIeni/release-plz/issues/615
I will add your pr as an example in that issue and close this one because it's a duplicate.

If you find a way to reproduce this issue, let me know so that it would be easier to debug.

**Comment by MarcoIeni** [comment] 2023-05-05 20:47
as a workaround, I think closing the pr and running release-plz again should work.

**Closed by MarcoIeni** 2023-05-05 20:47 UTC
Labels: bug

**Comment by MarcoIeni** [comment] 2023-05-05 20:50
Here are the [logs](https://github.com/flying-sheep/xdot-rs/actions/runs/4892993669/jobs/8735412250):

```
  2023-05-05T11:44:29.563305Z  INFO  xdot: next version is 0.2.4 (✓ API compatible changes)
    in packages_to_update
    in next_versions with input=UpdateRequest { local_manifest: "/tmp/.tmpaZVcIc/xdot-rs/Cargo.toml", registry_manifest: None, single_package: None, changelog_req: ChangelogRequest { release_date: None, changelog_config: None }, registry: None, dependencies_update: false, allow_dirty: false, repo_url: Some(RepoUrl { scheme: "https", host: "github.com", port: None, owner: "flying-sheep", name: "xdot-rs" }), packages_config: PackagesConfig { default: UpdateConfig { semver_check: Lib, changelog_update: true }, overrides: {} } }
    in update with input=UpdateRequest { local_manifest: "/tmp/.tmpaZVcIc/xdot-rs/Cargo.toml", registry_manifest: None, single_package: None, changelog_req: ChangelogRequest { release_date: None, changelog_config: None }, registry: None, dependencies_update: false, allow_dirty: false, repo_url: Some(RepoUrl { scheme: "https", host: "github.com", port: None, owner: "flying-sheep", name: "xdot-rs" }), packages_config: PackagesConfig { default: UpdateConfig { semver_check: Lib, changelog_update: true }, overrides: {} } }
    in release_pr with input=ReleasePrRequest { git: Github(GitHub { remote: Remote { owner: "flying-sheep", repo: "xdot-rs", token: Secret([REDACTED alloc::string::String]), base_url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("api.github.com")), port: None, path: "/", query: None, fragment: None } } }), labels: [], update_request: UpdateRequest { local_manifest: "/home/runner/work/xdot-rs/xdot-rs/Cargo.toml", registry_manifest: None, single_package: None, changelog_req: ChangelogRequest { release_date: None, changelog_config: None }, registry: None, dependencies_update: false, allow_dirty: false, repo_url: Some(RepoUrl { scheme: "https", host: "github.com", port: None, owner: "flying-sheep", name: "xdot-rs" }), packages_config: PackagesConfig { default: UpdateConfig { semver_check: Lib, changelog_update: true }, overrides: {} } } }

    Updating xdot v0.2.3 (/tmp/.tmpaZVcIc/xdot-rs) -> v0.2.4
  2023-05-05T11:44:30.878025Z ERROR  cannot rebase from default branch: error while running git with args `["rebase", "main"]:
- stdout: Auto-merging .gitignore
CONFLICT (add/add): Merge conflict in .gitignore
Auto-merging Cargo.lock
CONFLICT (add/add): Merge conflict in Cargo.lock
Auto-merging Cargo.toml
CONFLICT (add/add): Merge conflict in Cargo.toml
- stderr: Rebasing (1/50)
error: could not apply dc55b10... WIP
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply dc55b10... WIP
    in release_pr with input=ReleasePrRequest { git: Github(GitHub { remote: Remote { owner: "flying-sheep", repo: "xdot-rs", token: Secret([REDACTED alloc::string::String]), base_url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("api.github.com")), port: None, path: "/", query: None, fragment: None } } }), labels: [], update_request: UpdateRequest { local_manifest: "/home/runner/work/xdot-rs/xdot-rs/Cargo.toml", registry_manifest: None, single_package: None, changelog_req: ChangelogRequest { release_date: None, changelog_config: None }, registry: None, dependencies_update: false, allow_dirty: false, repo_url: Some(RepoUrl { scheme: "https", host: "github.com", port: None, owner: "flying-sheep", name: "xdot-rs" }), packages_config: PackagesConfig { default: UpdateConfig { semver_check: Lib, changelog_update: true }, overrides: {} } } }

  2023-05-05T11:44:30.880562Z ERROR  cannot update release pr 27: error while running git with args `["stash", "pop"]:
- stdout: .gitignore: needs merge
Cargo.lock: needs merge
Cargo.toml: needs merge
The stash entry is kept in case you need it again.. I'm closing the old release pr and opening a new one
    in release_pr with input=ReleasePrRequest { git: Github(GitHub { remote: Remote { owner: "flying-sheep", repo: "xdot-rs", token: Secret([REDACTED alloc::string::String]), base_url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("api.github.com")), port: None, path: "/", query: None, fragment: None } } }), labels: [], update_request: UpdateRequest { local_manifest: "/home/runner/work/xdot-rs/xdot-rs/Cargo.toml", registry_manifest: None, single_package: None, changelog_req: ChangelogRequest { release_date: None, changelog_config: None }, registry: None, dependencies_update: false, allow_dirty: false, repo_url: Some(RepoUrl { scheme: "https", host: "github.com", port: None, owner: "flying-sheep", name: "xdot-rs" }), packages_config: PackagesConfig { default: UpdateConfig { semver_check: Lib, changelog_update: true }, overrides: {} } } }

  2023-05-05T11:44:33.934200Z  INFO  opened pr: https://github.com/flying-sheep/xdot-rs/pull/29
    in open_pr
    in release_pr with input=ReleasePrRequest { git: Github(GitHub { remote: Remote { owner: "flying-sheep", repo: "xdot-rs", token: Secret([REDACTED alloc::string::String]), base_url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("api.github.com")), port: None, path: "/", query: None, fragment: None } } }), labels: [], update_request: UpdateRequest { local_manifest: "/home/runner/work/xdot-rs/xdot-rs/Cargo.toml", registry_manifest: None, single_package: None, changelog_req: ChangelogRequest { release_date: None, changelog_config: None }, registry: None, dependencies_update: false, allow_dirty: false, repo_url: Some(RepoUrl { scheme: "https", host: "github.com", port: None, owner: "flying-sheep", name: "xdot-rs" }), packages_config: PackagesConfig { default: UpdateConfig { semver_check: Lib, changelog_update: true }, overrides: {} } } }

```

**Comment by flying-sheep** [comment] 2023-05-09 13:07
> as a workaround, I think closing the pr and running release-plz again should work.

hmm, I already closed an earlier PR like this.

>  2023-05-05T11:44:30.878025Z ERROR  cannot rebase from default branch: error while running git with args `["rebase", "main"]:

What causes this? `release-plz` is run by CI on a clone from `main`. Where does it get the commit from that it tries do apply its changes to?
