### ISSUE TITLE
Release PR cannot be pushed when remote had changes meanwhile

### ISSUE THREAD

**Issue by sassman** [MarcoIeni/release-plz#606] opened 2023-03-15 08:31 UTC
## Bug description

A bit hard to describe, but there was one [particular release PR run](https://github.com/curlz-rs/curlz/actions/runs/4421328543/jobs/7751995051) that failed with this error:

```plain
    Updating curlz v0.1.0-alpha.10 (/tmp/.tmp3rHner/curlz/curlz) -> v0.1.0-alpha.11
  2023-03-15T00:05:56.588142Z ERROR  error while running git with args `["push", "origin", "release-plz/2023-03-15T00-05-55Z"]:
- stderr: To https://github.com/curlz-rs/curlz
 ! [remote rejected] release-plz/2023-03-15T00-05-55Z -> release-plz/2023-03-15T00-05-55Z (refusing to allow a GitHub App to create or update workflow `.github/workflows/build.yml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/curlz-rs/curlz'
```

The essence is that meanwhile, the remote site got changes (particularly on some GitHub Actions), that prevented release-plz from pushing a branch that does not yet have those changes.

I know it's a bit of a corner case, so I guess it's really low priority.

- Would you like to work on a fix? [y/n]

## To Reproduce

1. merge a PR
2. have release-plz running and preparing a release PR
3. meanwhile merge another PR that has changes on a GitHub Action pipeline
4. see that the ongoing release PR prep (step 2.) encountered the error

## Expected behavior

I would assume that before pushing the release PR branch `release-plz/2023-03-15T00-05-55Z`
a git pull and rebase would prevent that from happening.

## Environment

on GitHub Actions

- OS: Ubuntu 22.04
- release-plz version: v0.2.55

**Comment by MarcoIeni** [comment] 2023-03-16 22:20
Hey Sven, thank you for all these reports, it really helps :)

[This](https://github.com/MarcoIeni/release-plz/blob/0b8f0d9b7170ba4830c5b1a9c88c8f82e4426858/crates/release_plz_core/src/release_pr.rs#L124) is how release-plz updates a pr. If you know a better way to update a branch that requires fewer permissions, please tell me.

In the meantime, I couldn't reproduce your issue [here](https://github.com/MarcoIeni/rust-workspace-example/commit/db686129175828026efd92d576c8943515964ac8).
Maybe because you don't have the permissions section in the yaml as suggested [here](https://github.com/MarcoIeni/release-plz/blob/main/docs/src/github-action.md#example-release-pr-and-release)?

**Comment by sassman** [comment] 2023-03-16 22:33
hm, from a quick look at the code I think I miss a `git fetch` before the `git rebase` takes place.

In order to make sure that you got all the changes from remote / upstream it would be best to do a `git fetch` first (also the git action `actions/checkout@v3` does this)
And then do a rebase on the `remote/<master|main>`.

**Comment by MarcoIeni** [comment] 2023-03-16 22:55
Like [this](https://github.com/MarcoIeni/release-plz/pull/607)? 🤔 
Anyway, for the reason I explained above in my edited comment (the lack of `--force` flag), I don't think that code was executed in your run.

Also, the fact that I initialize the default branch to the current one [here](https://github.com/MarcoIeni/release-plz/blob/0b8f0d9b7170ba4830c5b1a9c88c8f82e4426858/crates/git_cmd/src/lib.rs#L34) seems bad, but it might be unrelated.

- [ ] I need to look into it.

**Comment by sassman** [comment] 2023-03-16 23:03
> Also, the fact that I initialize the default branch to the current one [here](https://github.com/MarcoIeni/release-plz/blob/0b8f0d9b7170ba4830c5b1a9c88c8f82e4426858/crates/git_cmd/src/lib.rs#L34) seems bad, but it might be unrelated.

https://github.com/MarcoIeni/release-plz/blob/0b8f0d9b7170ba4830c5b1a9c88c8f82e4426858/crates/git_cmd/src/lib.rs#L34

So locally that might be an issue, depending on the current branch, you would want to do the rebase always against the `mainline` branch of the repo from the remote side. 
Tricky would be when multiple remotes are registered.

On CI the stuff runs after the checkout (a fresh checkout) that would leave the current branch on the mainline, then it should work all fine.

**Comment by sassman** [comment] 2023-03-16 23:04
So I'm pretty sure that the `git fetch` would prevent from missing out on "meanwhile-new-commits-on-upstream"

**Comment by MarcoIeni** [comment] 2023-03-17 23:42
I have released a new version of release-plz that includes the git fetch.
Please, tell me if it solved your issue.

**Comment by MarcoIeni** [comment] 2023-04-05 19:59
I'm closing this issue to keep the issue tracker clean.
Please, reopen this if you think it's not solved yet.

**Closed by MarcoIeni** 2023-04-05 19:59 UTC
Labels: bug
