### ISSUE TITLE
release-plz is unable to gpg sign git tags

### ISSUE THREAD

**Issue by VorpalBlade** [MarcoIeni/release-plz#1310] opened 2024-02-26 21:55 UTC
## Bug description

Git tags that release-plz produces are not gpg-signed, if you enable signed tags in your .gitconfig it instead hangs. That is quite a serious oversight in my opinion.

- Would you like to work on a fix? [y/n] I mean, if I want to be able to use this software it is either that or wait for you to implement it.

## To Reproduce

Have this in your `~/.gitconfig`
```ini
[tag]
    gpgSign = true
```

1. `release-plz release`
2. release-plz hangs and never adds a tag.

## Expected behavior

Sign the tag? I have a gpg-agent running after all...

## Screenshots

```
note: Waiting for `paketkoll v0.1.2` to be available at registry `crates-io`.
You may press ctrl-c to skip waiting; the crate should be available shortly.
   Published paketkoll v0.1.2 at registry `crates-io`
<hangs here for minutes>
```

## Environment

- OS: Arch Linux
- release-plz version: 0.3.48

**Comment by MarcoIeni** [comment] 2024-02-27 06:25
Duplicate of https://github.com/MarcoIeni/release-plz/issues/1215

**Closed** 2024-02-27 06:27 UTC
Labels: bug
