### ISSUE TITLE
Changelog not updated

### ISSUE THREAD

**Issue by Alxandr** [MarcoIeni/release-plz#1185] opened 2024-01-03 22:27 UTC
## Bug description

I'm trying out release-plz on [a project](https://github.com/YoloDev/rstml-component) of mine (previously using release-please), but the changelog is not being updated. I'm not sure what's wrong, and would love some help/suggestions. The latest release-pr can be seen here: https://github.com/YoloDev/rstml-component/pull/18.

This is most likely related to me having changed the git-cliff config (I need a couple of non-standard groups), but I can't for the life of me figure out how to add custom groups and also get a changelog generated.

- Would you like to work on a fix? [y/n] Hopefully this isn't something that needs "work on" - but just documentation/help.

## To Reproduce

1. ... ues release-plz with custom git-cliff commit_parsers configured

## Expected behavior

The PR should include update to the changelog.

## Environment

- OS: github ubuntu-latest
- release-plz version: github action latest

**Comment by MarcoIeni** [comment] 2024-01-07 13:02
The issue is that for now you need to specify also the `[changelog]` section like it's done [here](https://github.com/orhun/daktilo/blob/main/cliff.toml) for example.
I'm working on a fix for this 👍

**Closed** 2024-01-27 23:22 UTC
Labels: bug
