### ISSUE TITLE
Can't publish to private registry (works with cargo publish)

### ISSUE THREAD

**Issue by scullionw** [MarcoIeni/release-plz#831] opened 2023-06-21 22:24 UTC
## Bug description

Can't publish to private registry (works with cargo publish)

## Expected behavior

I would expect the crates to be published like they are with `cargo publish` or `cargo release`

## Screenshots

<img width="1458" alt="Screenshot 2023-06-21 at 6 22 59 PM" src="https://github.com/MarcoIeni/release-plz/assets/11668344/2776c529-7377-4984-8009-da3d64dd9f55">

## Environment

- OS: macOS 13.3
- release-plz version: release-plz 0.3.14

**Comment by MarcoIeni** [comment] 2023-06-22 05:58
Thanks for the report, I will try to reproduce and fix this 👍

**Comment by Kelwing** [comment] 2023-07-20 18:48
@MarcoIeni I looked into this because I was running into the same issue.  It's caused when the private registry is configured using a sparse protocol url instead of a git url.  release-plz only uses the git index from`crates_index` and tries to  initialize the Index object from a sparse registry URL.
 https://github.com/MarcoIeni/release-plz/blob/main/crates/release_plz_core/src/command/release.rs#L315

**Comment by MarcoIeni** [comment] 2023-07-20 20:08
Thanks for looking into this. I'll try to look into this next week.

**Comment by MarcoIeni** [comment] 2023-07-23 21:13
I'm trying to check if #863 fixed this issue.
- scullionw, can you try if that branch fixes your issue?
- Kelwing, can you tell me how have you tested it?

I registered to `shipyard.rs`, I added this to my .cargo/config.toml:

```toml
[registries.ieni]
index = "ssh://git@ssh.shipyard.rs/ieni/crate-index.git"

[net]
git-fetch-with-cli = true

[http]
user-agent = "shipyard <token>"
```

and I created an ssh key pair.

However both release-plz and cargo publish are failing for me.

```
$ cargo publish --registry ieni
    Updating `ieni` index
git@ssh.shipyard.rs: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: failed to update registry `ieni`

Caused by:
  failed to fetch `ssh://git@ssh.shipyard.rs/ieni/crate-index.git`

Caused by:
  process didn't exit successfully: `git fetch --force --update-head-ok 'ssh://git@ssh.shipyard.rs/ieni/crate-index.git' '+HEAD:refs/remotes/origin/HEAD'` (exit status: 128)
```

Probably I'm missing something from the configuration.

**Comment by MarcoIeni** [comment] 2023-07-25 18:03
reopening, because I'm not sure the linked pr fixed the issue

**Comment by Kelwing** [comment] 2023-07-25 22:31
That's the same behavior and error I was seeing when I tried using a sparse URL without support for it.  The crate_index package would attempt to treat it as if it were a git repo.

**Comment by MarcoIeni** [comment] 2023-08-20 09:59
In https://github.com/MarcoIeni/release-plz/pull/892 I added a test where I publish a crate to the gitea private cargo [registry](https://docs.gitea.com/next/usage/packages/cargo) which runs in docker.
This demonstrates that release-plz can publish to private registries, so I'm closing this issue.
If you find issues with other cargo registries, please open another issue with a step-by-step reproduction guide (e.g. register to this website, click here, use a certain `config.toml`, etc.).
Thanks everyone 🙏

**Closed by MarcoIeni** 2023-08-20 09:59 UTC
Labels: bug
