### ISSUE TITLE
Allow to not publish new package not as latest or as pre-release

### ISSUE THREAD

**Issue by kaihowl** [MarcoIeni/release-plz#1219] opened 2024-01-20 18:39 UTC
## Motivations

When the PR for a new release is merged, a git tag and a github release is created. Only with a second action, I can add the necessary compiled assets for multiple platforms for the release. In this short period while the second action is building all assets, consumers will see the "latest" release without any assets for it.

- Would you like to implement this feature? Can't say yet.

## Solution

Allow setting a release as a prerelease. Similar to the `git_release_draft` option have a `git_release_prerelease`.

## Alternatives

- We could publish a draft release. Unfortunately, I cannot upload assets to it with a github action.
- We could publish a pre-release package. This works but might look odd as "prerelease". Once the assets are uploaded, the release could be made "latest" and no longer "prerelease".
- We could publish a normal release and simply not set it as "latest". Once the assets are uploaded, the release could be marked as "latest".

The second and third option sound very similar. If someone were to find the "in flight" release, a clearly marked "pre-release" might look less suspicious than a release with a higher version, which is not marked as "latest".

## Additional context

Issue #420 looks very similar, although I understand it was related to having multiple packages from a workspace published from the same repository.

**Comment by MarcoIeni** [comment] 2024-01-20 20:17
Duplicate of https://github.com/MarcoIeni/release-plz/issues/678

Please correct me if I'm wrong here :)

**Comment by MarcoIeni** [comment] 2024-01-20 20:18
In case you want to raise a PR, it's an easy issue!
You can take a look at https://github.com/MarcoIeni/release-plz/pull/986 for inspiration

**Closed by MarcoIeni** 2024-01-20 20:17 UTC
Labels: enhancement

**Comment by kaihowl** [comment] 2024-01-20 21:04
@MarcoIeni, this is indeed a duplicate. I only search for duplicates about `latest` and forgot to check about `prerelease`. Sorry about that. :)
