### ISSUE TITLE
Add a feature to generate a full changlog

### ISSUE THREAD

**Issue by TerakomariGandesblood** [MarcoIeni/release-plz#1600] opened 2024-08-09 02:58 UTC
## Motivations

Because my project didn't use release-plz from the beginning, its changlog format doesn't exactly match the one generated by release-plz.
I want to regenerate a complete changlog, does release-plz have this feature? Or is it possible for you to add this feature?

## Solution

Add a flag to the `update` subcommand, such as `--full-changelog`, so that it overwrites the existing (or non-existent) changelog.

## Alternatives

Alternatively, you can export the git-cliff configuration used by release-plz as a cliff.toml file, so that you can run git-cliff manually to generate the changelog

**Comment by MarcoIeni** [comment] 2024-08-09 07:29
Duplicate of https://github.com/MarcoIeni/release-plz/issues/1009

**Closed by MarcoIeni** 2024-08-09 07:29 UTC
Labels: enhancement
